models:
  - name: "llm"
    model: "Qwen/Qwen3-8B-AWQ"
    usecase: "generate"
    loader: "vllm"
    num_gpus: 0.55

  - name: "kokoro"
    model: "kokoro-en-v0_19"
    usecase: "tts"
    loader: "sherpa_onnx"
    num_gpus: 0
    num_cpus: 2

  - name: "whisper"
    model: "openai/whisper-large-v3-turbo"
    usecase: "transcription"
    loader: "vllm"
    num_gpus: 0.15
    vllm_engine_kwargs:
      trust_remote_code: true

  - name: "nomic-embed"
    model: "nomic-ai/nomic-embed-text-v1.5"
    usecase: "embed"
    loader: "vllm"
    num_gpus: 0.10
    vllm_engine_kwargs:
      trust_remote_code: true
