models:
  - name: "qwen"
    model: "lmstudio-community/Qwen3-8B-GGUF:*Q4_K_M.gguf"
    usecase: "generate"
    loader: "llama_server"
    num_cpus: 3
    llama_server_config:
      parallel: 4

  - name: "qwen-local"
    model: "/.cache/huggingface/qwen3-8b-instruct.Q4_K_M.gguf"
    usecase: "generate"
    loader: "llama_server"
    num_cpus: 4
    llama_server_config:
      parallel: 2

  - name: "qwen-vl"
    model: "lmstudio-community/Qwen3-VL-8B-Instruct-GGUF:*Q4_K_M.gguf"
    usecase: "generate"
    loader: "llama_server"
    num_cpus: 3
    llama_server_config:
      mmproj: "lmstudio-community/Qwen3-VL-8B-Instruct-GGUF:mmproj-Qwen3-VL-8B-Instruct-F16.gguf"

  - name: "llama-70b-q8"
    model: "bartowski/Llama-3.3-70B-Instruct-GGUF:*Q8_0*-of-*.gguf"
    usecase: "generate"
    loader: "llama_server"
    num_gpus: 1
    llama_server_config:
      parallel: 2

  - name: "nomic-embed"
    model: "nomic-ai/nomic-embed-text-v1.5-GGUF:nomic-embed-text-v1.5.Q4_K_M.gguf"
    usecase: "embed"
    loader: "llama_server"
    num_cpus: 2
