models:
  - name: "kokoro"
    model: "kokoro-en-v0_19"
    usecase: "tts"
    loader: "sherpa_onnx"
    num_cpus: 2

  - name: "kokoro-multi-lang"
    model: "kokoro-multi-lang-v1_0"
    usecase: "tts"
    loader: "sherpa_onnx"
    num_cpus: 2

  - name: "kokoro-local"
    model: "/models/kokoro-en-v0_19"
    usecase: "tts"
    loader: "sherpa_onnx"
    num_cpus: 2
