models:
  - name: "sd21-turbo"
    model: "gpustack/stable-diffusion-v2-1-turbo-GGUF:*Q4_1.gguf"
    usecase: "image"
    loader: "stable_diffusion_cpp"
    num_cpus: 4
    stable_diffusion_cpp_config:
      sample_steps: 4
      cfg_scale: 1.0

  - name: "flux-schnell"
    model: "/.cache/models/flux1-schnell-q4_k.gguf"
    usecase: "image"
    loader: "stable_diffusion_cpp"
    num_cpus: 6
    stable_diffusion_cpp_config:
      sample_steps: 4
      cfg_scale: 1.0
