models:
  - name: "llm"
    model: "Qwen/Qwen3-8B-AWQ"
    usecase: "generate"
    loader: "vllm"
    num_gpus: 0.7

  - name: "nomic-embed"
    model: "nomic-ai/nomic-embed-text-v1.5"
    usecase: "embed"
    loader: "vllm"
    num_gpus: 0.1
    vllm_engine_kwargs:
      trust_remote_code: true

  - name: "whisper"
    model: "openai/whisper-large-v3-turbo"
    usecase: "transcription"
    loader: "vllm"
    num_gpus: 0.25
    vllm_engine_kwargs:
      trust_remote_code: true

  - name: "bursty-llm"
    model: "Qwen/Qwen3-8B-AWQ"
    usecase: "generate"
    loader: "vllm"
    num_gpus: 0.5
    autoscaling_config:
      min_replicas: 1
      max_replicas: 4
      target_ongoing_requests: 8
      upscale_delay_s: 10
      downscale_delay_s: 600
