models:
  - name: "whisper-cpp-tiny"
    model: "tiny.en"
    usecase: "transcription"
    loader: "whispercpp"
    num_cpus: 1

  - name: "whisper-cpp-base"
    model: "ggerganov/whisper.cpp:ggml-base.en.bin"
    usecase: "transcription"
    loader: "whispercpp"
    num_cpus: 2
    whispercpp_config:
      n_threads: 2

  - name: "whisper-cpp-local"
    model: "/.cache/huggingface/ggml-base.en.bin"
    usecase: "transcription"
    loader: "whispercpp"
    num_cpus: 2

  - name: "whisper-cpp-metal"
    model: "base.en"
    usecase: "transcription"
    loader: "whispercpp"
    num_gpus: 1
